FROM ubuntu:26.04

ENV container=docker
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        ca-certificates \
        dbus \
        python3 \
        sudo \
        systemd \
        systemd-sysv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && find /etc/systemd/system \
        /lib/systemd/system \
        -path '*.wants/*' \
        -not -name systemd-tmpfiles-setup.service \
        -not -name systemd-journald.service \
        -not -name systemd-remount-fs.service \
        -delete

STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
